consumers:
- username: simon
- username: jack

llms:
  - name: gemini-1.5-pro
    route_type: "llm/v1/chat"
    base_path: /chat/completions
    llm_format: openai
    targets:
      - model:
          name: gemini-1.5-pro
          provider: gemini
          options:
            gemini:
              api_endpoint: ${ GEMINI_API_ENDPOINT }
              project_id: ${ GEMINI_PROJECT_ID }
              location_id: ${ GEMINI_LOCATION_ID }
        auth:
          gcp_use_service_account: true
          allow_override: false
        logging:
          log_payloads: false
          log_statistics: true
    tshirt:
      large:
        limit:
          - 100000
        window_size:
          - 3600
      medium:
        limit:
          - 5000
        window_size:
          - 60
      small:
        limit:
          - 2000
          - 86400
        window_size:
          - 60
          - 100000
  - name: gemini-2.5-flash
    route_type: "llm/v1/chat"
    base_path: /chat/completions
    llm_format: openai
    targets:
      - model:
          name: gemini-2.5-flash
          provider: gemini
          options:
            gemini:
              api_endpoint: ${ GEMINI_API_ENDPOINT }
              project_id: ${ GEMINI_PROJECT_ID }
              location_id: ${ GEMINI_LOCATION_ID }
        auth:
          gcp_use_service_account: true
          allow_override: false
        logging:
          log_payloads: false
          log_statistics: true
    tshirt:
      large:
        limit:
          - 100000
        window_size:
          - 3600
      medium:
        limit:
          - 5000
        window_size:
          - 60
      small:
        limit:
          - 5000
          - 86400
        window_size:
          - 60
          - 200000
