llms:
  - name: gemini-1.5-pro
    base_path: /chat/completions
    llm_format: openai
    targets:
      - model:
          name: gemini-1.5-pro
          provider: gemini
          options:
            gemini:
              api_endpoint: ${ GEMINI_API_ENDPOINT }
              project_id: ${ GEMINI_PROJECT_ID }
              location_id: ${ GEMINI_LOCATION_ID }
        auth:
          gcp_use_service_account: true
          allow_override: false
        logging:
          log_payloads: false
          log_statistics: true
  - name: gemini-2.5-flash
    base_path: /chat/completions
    llm_format: openai
    targets:
      - model:
          name: gemini-2.5-flash
          provider: gemini
          options:
            gemini:
              api_endpoint: ${ GEMINI_API_ENDPOINT }
              project_id: ${ GEMINI_PROJECT_ID }
              location_id: ${ GEMINI_LOCATION_ID }
        auth:
          gcp_use_service_account: true
          allow_override: false
        logging:
          log_payloads: false
          log_statistics: true
